name: Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Get project name and version
        id: gradle-info
        run: |
          echo "PROJECT_NAME=$(./gradlew -q printProjectName)" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI Action to deploy to dev with main branch
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az spring app deploy \
            --resource-group rg-ledencentraal-sapp-sql\
            --service ledencentraal-backend-service\
            --name spring-app-20240319180921 \
            --artifact-path ${{ github.workspace }}/build/libs/*.jar \
            --runtime-version Java_17 \
            --jvm-options='-Dspring.profiles.active=dev'


      - name: Logout from Azure
        run: az logout
