name: Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Spring Apps
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group: 'ledencentraal-spring-env_SpringApps_e1db83d8-84cb-4d46-a764-5ae6a36f331b'
          action: 'Deploy'
          app-name: 'spring-app-20240319180921'
          use-staging-deployment: true
          package: './build/libs/${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.jar'
          environment: 'Staging'

      - name: Logout from Azure
        run: az logout
