name: Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Get project name and version
        id: gradle-info
        run: |
          echo "PROJECT_NAME=$(./gradlew -q printProjectName)" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t myusername/myapp:${{ github.run_number }} \
          --build-arg JAR_FILE=./build/libs/${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.jar \
          .


      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Action to deploy to dev with main branch
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az spring app deploy \
            --resource-group ${{vars.AZURE_RESOURCE_GROUP}} \
            --service ${{vars.AZURE_SERVICE_NAME}} \
            --name ${{vars.AZURE_APP_NAME}} \
            --artifact-path './build/libs/${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.jar' \
            --runtime-version ${{vars.AZURE_RUNTIME_VERSION}} \
            --jvm-options='-Dspring.profiles.active=dev'

      - name: Logout from Azure
        run: az logout

      - name: Error handling
        if: failure()
        run: echo "Deployment failed. Please check the logs above."
